services:
  web:
    build:
      context: ./server  
      dockerfile: Dockerfile  
    container_name: django_web
    volumes:
      - ./server:/app 
      - static_volume:/app/static 
    expose:
      - 8000
  
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  static_volume:
