services:
  web:
    build:
      context: ./server  
      dockerfile: Dockerfile  
    container_name: django_web
    volumes:
      - ./server:/app  
    expose:
      - 8000
  
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx_proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web